on: push
name: 🚀 Deploy website B on push
jobs:
  web-deploy:
    name: 🎉 Deploy B
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files B
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: ${{ secrets.ftp_b_server }}
        username: ${{ secrets.ftp_b_username }}
        password: ${{ secrets.ftp_b_password }}
        protocol: ftps
